name = "metallum-telemetry"
main = "src/index.js"
compatibility_date = "2026-07-29"

[observability]
enabled = false

[[d1_databases]]
binding = "DB"
database_name = "metallum-telemetry"
database_id = "cf39fc79-794f-440d-bfca-c83c782f1319"
